sequenceDiagram
participant Edge
participant PRacc
participant Proxy
participant NSM
participant ASDy

    Edge  ->>  PRacc : partial_read([SCOx, off, 4096])
    PRacc ->>  Proxy : partial_read([SCOx, off, 4096])
    Proxy ->>  NSM   : get_manifest(SCOx)
    NSM   -->> Proxy : mf
    Proxy ->>  ASDy  : partial_read([fragment_t, off, 4096])
    ASDy  -->> Proxy : [data]
    Proxy -->> PRacc : [data], mf
    PRacc -->> Edge  : [data]
